### ISSUE TITLE
Expo Go supports only SDK version > 48

### ISSUE THREAD

**Issue by paulaubin** [eleurent/nature-go#40]
Hi guys,

Edouard told me about this game and I am really looking forward to try it one day. I tried to register through the Expo app on my smartphone (Android Pixel 8) but I got an error message :
"
Project is incompatible with this version of Expo Go
"
The current versions supported by Expo Go are 49 or higher and it seems that this project's version is 48

All the best

**Comment by eleurent** [comment]
Hey, nice to see you here! :)

I had updated to SDK 50, but turns out the SDK was hardcoded in the qr code url for some reason...
You should be able to try it now, but remember that:

- This project is still very much WIP
- There are a couple bugs that appeared with the SDK 48 --> 50 transition that I need to fix
- The Bird ID is not functional yet (as of now you have to select a species manually out of the 300 most common), but Gemini APIs FINALLY JUST GOT AVAILABLE in Europe at Google I/O last Tuesday, so I should be able to make it work when I find the time.
